### ISSUE TITLE
Almost final issues - updated

### ISSUE THREAD

**Issue by jdbaltazar** [jdbaltazar/CMSC-198-IAPPSAM-System#51]
Employee
- divisionoffice value not included in search

APP
- for export as PDF and Excel, include the designations of the signatories
- for export as Excel, borders need to be fixed
- for export as Excel, year must be beside (not above) "Annual Procurement Plan" text

PR
- export as excel, borders need to be fixed

RIS
- in export as excel, the requested, approved and issued by dates
  are not indicated

**Comment by jkdeveyra** [comment]
Fixed everything except for the first one. No Searching function in forms
